### ISSUE TITLE
CHAPTER 2 동작 파라미터화 코드 전달하기

### ISSUE THREAD

**Issue by alanhakhyeonsong** [NHS-Developers-Meeting/modern-java-in-action#4]
chapter 2를 읽고 질문 거리들을 남겨주세요

**Comment by KIMHYOJUN97** [comment]
동적 파라미터화 개념 나온김에 리플렉션과 관련된 개념 인지하기!
제네릭스와 Object의 차이점, 제네릭스와 리플렉션의 차이점!

**Comment by alanhakhyeonsong** [comment]
Java Reflection에 관련한 첫 번째 질문에 대해 간단히 답변을 하자면,
→ [`Class<T>`, Java 8 docs](https://docs.oracle.com/javase/8/docs/api/java/lang/Class.html)

### `Class<T>`에 접근하는 방법?
- 모든 클래스를 로딩한 다음 `Class<T>`의 인스턴스가 생긴다. 이 경우 `타입.class`로 접근할 수 있다.

```java
Class<Book> bookClass = Book.class;
```

- 모든 인스턴스는 `getClass()` 메소드를 가지고 있다. 이 경우 `인스턴스.getClass()`로 접근할 수 있다.

```java
Book book = new Book();
Class<? extends Book> aClass = book.getClass();
```

- 클래스를 문자열로 읽어오는 방법은 다음과 같다.
  - `Class.forName("FQCN")`
  - 클래스패스에 해당 클래스가 없다면 `ClassNotFoundException`이 발생한다.

```java
Class<?> aClass1 = Class.forName("me.ramos.Book");
```

- `Class<T>`를 통해 할 수 있는 것
  - 필드(목록) 가져오기
  - 메소드(목록) 가져오기
  - 상위 클래스 가져오기
  - 인터페이스 (목록) 가져오기
  - 애노테이션 가져오기
  - 생성자 가져오기
  - ...

**Comment by alanhakhyeonsong** [comment]
두 번째 질문에 대해 간단히 답변을 하자면,
- 제네릭스와 Object의 차이점
  → `new`, `instanceof` 연산자 제한, `static` 키워드와 관련한 동작 방식의 차이를 찾아보세요.
- 제네릭스와 리플렉션의 차이점
  → 동작 시점의 차이: 컴파일 타임 vs 런타임
