### ISSUE TITLE
CHAPTER 4 스트림 소개

### ISSUE THREAD

**Issue by alanhakhyeonsong** [NHS-Developers-Meeting/modern-java-in-action#8]
chapter 4을 읽고 요약한 것을 main에 올려주시고, 질문 거리들을 해당 issue에 남겨주세요.

**Comment by KIMHYOJUN97** [comment]
스트림 병렬 처리의 내부 동작 방식. - 이후 챕터에서 나오는 주제
중간 연산의 처리가 안된다는 건, 실수로 최종 연산을 쓰지 않았을 때를 의미하는 것인지?->이게 게으름의 의미인지
투명성의 정확한 의미

**Comment by alanhakhyeonsong** [comment]
Q. 스트림 병렬 처리의 내부 동작 방식
A. 이후 챕터에 등장하는 fork-join 프레임워크에 대해 학습해보세요.

Q. '중간 연산의 처리가 안된다'라는 의미?
A. 중간 연산 메소드들의 반환 타입이 'Stream<T>'인데, 최종 연산을 하기 전까진 소비(처리)를 하지 않고 그대로 Stream의 형태로 남아있다고 보는게 올바를 것 같습니다. 생각하신대로 게으름의 의미도 이에 대한 연장선이기도 합니다. 루프와 관련된 연산을 할 때, Collection은 매 요소 각각을 연산하는 반면, Stream은 최종 연산을 하기 전까진 스트림에 쌓아두고 한 번에 처리한다고 보시면 될 것 같네요. 이게 되게 중요한 특징인게, 불필요한 호출이 적어지고 결과적으로 성능 향상에 이점이 있지요. (무한 스트림의 경우 메모리 이슈도 피할 수 있음)

Q. 투명성의 정확한 의미. 
A. Stream API가 없던 이전 Java 버전에선 병렬처리를 멀티스레드 코드로 굉장히 복잡하게 처리하곤 했는데, `parallelStream()`을 사용하면 이런 복잡한 처리 없이 투명하고 깔끔하게 처리할 수 있기 때문에 '투명성'이란 단어가 등장했다고 보면 될 것 같아요.
